export const RECIEVED_JOINABLE_GAMES_DATA = 'RECIEVED_JOINABLE_GAMES_DATA';
export const NICKNAME_CONFIRMED = 'NICKNAME_CONFIRMED';
export const JOINED_GAME = 'JOINED_GAME';
export const CREATED_GAME = 'CREATED_GAME';
export const TOGGLED_SLOT_OPEN_CLOSED = 'TOGGLED_SLOT_OPEN_CLOSED';
export const SWITCHED_PLAYER_SLOT = 'SWITCHED_PLAYER_SLOT';
export const KICKED_FROM_GAME = 'KICKED_FROM_GAME';
export const LEFT_GAME = 'LEFT_GAME';